# ==========================================
# tp-net-node-launch Configuration
# ==========================================

# --- Launch ---
launch.runtime.delay=1000

# --- Update ---
update.repo.url=https://github.com/tungttsmd/tp-net-node-release/archive/refs/heads/staging.zip
update.staging.timeout=30
update.backup.maxCount=2

# --- Staging ---
staging.console.debug=false

# --- Watchdog ---
watchdog.maxRestarts=5
watchdog.restartDelay=1000
watchdog.waitForProcessExitcode=2000
watchdog.launchDelay=5000

# --- Managed Processes ---
processes.0.name=tp-net-node-cloudflared-service
processes.0.cmd=current\\tp-net-node-cloudflared-service\\run.bat

processes.1.name=tp-net-libreHwMonitor
processes.1.cmd=current\\tp-net-libreHwMonitor\\run.bat

processes.2.name=tp-net-trigger
processes.2.cmd=current\\tp-net-trigger\\run.bat

# Thêm process cứ viết processes.3.name và processes.3.cmd (nơi chỉ định tên và lệnh để chạy) .... tương tự